{% set name = "pbs-installer" %}
{% set version = "2024.4.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pbs_installer-{{ version }}.tar.gz
  sha256: 19224733068b0ffa39b53afbb61544bee8ecb9503e7222ba034f07b9913e2c1c

build:
  entry_points:
    - pbs-install = pbs_installer.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-backend
    - pip
  run:
    - python >=3.8

test:
  imports:
    - pbs_installer
  commands:
    - pip check
    - pbs-install --help
  requires:
    - pip

about:
  home: https://github.com/frostming/pbs-installer
  summary: Installer for Python Build Standalone
  license: MIT
  license_file: LICENSE
  doc_url: https://pbs-installer.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - daylinmorgan
