{% set name = "pbs-installer" %}
{% set version = "2025.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pbs_installer-{{ version }}.tar.gz
  sha256: 4c9741e4ec2290e2728d41a86621d11d52b7e753efd93bf5a908a3e15801463d

build:
  entry_points:
    - pbs-install = pbs_installer.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - pbs_installer
  commands:
    - pip check
    - pbs-install --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/frostming/pbs-installer
  summary: Installer for Python Build Standalone
  license: MIT
  license_file: LICENSE
  doc_url: https://pbs-installer.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - daylinmorgan
